### ISSUE TITLE
issue with suggestions in scripts

### ISSUE THREAD

**Issue by ahemed-haneen** [lifeart/els-intl-addon#1]
suggestions are working fine in templates
but i couldn't get them to work in js

and also

```

    You can write translation result and it will be replaced to path.

'some.translation.path': 'Translation result'

{{t 'Translati..'}} -> {{t 'some.translation.path'}}

```
i couldn't understand what this would do
having translation suggestions is awesome. but i mostly handle my translations in the script

**Comment by lifeart** [comment]
Hi, @TheLooseCannon! Thank you for report! Could you send small not working code part?

By default addon has support for `t('foo')` calls, https://github.com/lifeart/els-intl-addon/blob/master/index.js#L11

**Comment by lifeart** [comment]
have seen same issue

**Comment by yratanov** [comment]
@lifeart this addon relies on existence of `ELSCompletionDummy` (as I understood a placeholder that indicates cursor position), but https://github.com/lifeart/ember-language-server doesn't add it to script files. So it probably should be changed there?

**Comment by yratanov** [comment]
I can add a quickfix PR that will allow to at least use autocompletion somehow in JS files, but it won't work if your cursor is inside of a string,
`this.intl.t("path_to|")` - will work
`this.intl.t("path_|to")` - won't work.

**Comment by lifeart** [comment]
@yratanov yes, we don't have it for JS files (because it's quite easy to break JS with this placeholder)
looks like we need to figure out way to support both cases

**Comment by lifeart** [comment]
version `1.0.5` published, @TheLooseCannon could you check it? Is it working for your case?
