### ISSUE TITLE
Autocomplete for Nested Translations

### ISSUE THREAD

**Issue by toovy** [lifeart/els-intl-addon#6]
Hi @lifeart, great addon! Helps a lot :). 

We encountered a bug/missing feature, as we decided to nest our translation files to keep our translation base clean and maintainable. With the nested structure the intellisense/autocomplete works correct for the root files (directly in translations/), but not in subfolders. We are using the latest v5 of ember-intl and yaml files.

📚 [Docs](https://ember-intl.github.io/ember-intl/docs/guide/translating-text#nested-translations)

In our example we have the file structure similar to this:
```
translations
  - components
    - companies
      - en-us.yml
```

When trying to autocomplete the path by typing {{t 'components.'}} there is no autocompletion. When typing the translated string, e.g. "Contacts", it autocompletes to the key which is relative to the file, e.g. the en-us.yml has ...

```
singular: Contact
plural: Contacts
```
... then it would complete to {{t 'plural'}} when choosing "Contacts" from the intellisense. The correct path is `components.companies.plural`. Seems like the nested files are scanned, but the path is not absolute.

Can you help with this? Thanks in advance!

**Comment by lifeart** [comment]
Hi @toovy! Thank you for request! This addon is already [integrated](https://github.com/lifeart/ember-language-server/pulls?q=is%3Apr+intl+is%3Aclosed) into core of ember-language server.

Try to remove it from app and check LS functionality, also, we have this PR, may be related to your case: https://github.com/lifeart/ember-language-server/pull/389

**Comment by toovy** [comment]
@lifeart ahh good to know! I'll check it out. Thanks!

**Comment by lifeart** [comment]
@toovy could you check latest version of vscode extension? Change should be shipped: https://github.com/lifeart/ember-language-server/pull/389

**Comment by toovy** [comment]
@lifeart sorry, pretty busy at the moment, I just updated Stable Ember Language Server (eELS), and now it is even worse. BTW. I'm on MacOs, with VS Code 1.69.2 and the uELS v3.0.33, I restarted VS code after the installation.

This is what I can see:

- same (incorrect) behaviour in TS files and HBS files
- trying to autocomplete gives results for both, the path autocompletion and the translation term autocompletion (i.e. the plugin at least runs and does some work)
- but still only the main YAML paths/translations are taken into consideration
- another bug might have been introduced, as the displayed paths in the intellisense and the autocompletion paths are incorrect, as they are absolute paths instead of relative paths now: `.Users.myusername.Dev.customers.my-customer.crm.client.translations.admin.countries` instead of `admin.countries`

Any idea?

**Comment by lifeart** [comment]
@toovy thank you for feedback! Let's jump to https://github.com/lifeart/ember-language-server/pull/389#issuecomment-1192541573 thread

**Comment by Pjaerr** [comment]
👋 Is there any update on nested files not getting intellisense/autocomplete?  @toovy do you still have this issue?

**Comment by toovy** [comment]
👋 @Pjaerr as already posted in https://github.com/lifeart/ember-language-server/pull/389 I've got not autocomplete for files in nested directory structures 😢

**Comment by lifeart** [comment]
Hi there!
@toovy, @Pjaerr if you could create failing test for this functionality (reference https://github.com/achambers/ember-language-server/blob/component-context-info-origin/test/bultin-addons/core/intl-providers-test.ts#L889), I could take a look

**Comment by Pjaerr** [comment]
Thanks for confirming @toovy  🙏 

@lifeart Thanks for your response...I will look into recreating a test case for this issue.

**Comment by Pjaerr** [comment]
@lifeart I can't get the test suite to run locally unfortunately. I was going to write the following test:

```
it('should provide translation hover for nested translation files (hbs)', async () => {
        const mockDirectory = {
          app: {
            components: {
              test: {
                'index.hbs': '<div>{{t "app.components.test.example"}}</div>',
              },
            },
          },
        };

        const nestedTranslations = {
          app: {
            components: {
              test: {
                'en-us.yaml': `example: 'Hello World'`,
              },
            },
          },
        };

        const result = (await getResult(
          HoverRequest.method,
          connection,
          { ...mockDirectory, translations: nestedTranslations },
          'app/components/test/index.hbs',
          {
            line: 0,
            character: 30,
          }
        )) as any;

        expect(result.response).toEqual({
          contents: {
            kind: 'plaintext',
            value: 'en-us : Hello World',
          },
        });
      });
```

This would be testing hover, but I guess the existing nested folders test for autocomplete (`#wrapTranslationsWithNamespace is true`) would cover this use case 🤔

**Comment by Pjaerr** [comment]
I'll try and look into this a bit more but maybe my scenario might help...I have the following folder structure:

```
translations/
├── app/
│   └── components/
│       └── en-us.yaml
├── common/
│   └── en-us.yaml
└── lib/
    └── components/
        └── en-us.yaml
```

in the editor I get hover and autocomplete support for any keys underneath `/lib` and `/common` but not on anything under `/app`

It doesn't matter what I name that directory it will only work for `lib` and `common` (or new folders)...maybe there's an issue with formatting in the files in the `/app` directory causing things to not work, although I can't seem to get it to work after an initial experiment.

If I get some time I will see about getting the language server extension working locally so I can try to debug 🙏
